module.exports = {
  "attention": [
    "bounce",
    "flash",
    "hatch",
    "head-shake",
    "jello",
    "pulse",
    "rubber-band",
    "shake",
    "swing",
    "tada",
    "wobble",
  ],
  "boing": [
    "boing-in-up",
    "boing-out-down",
  ],
  "bomb": [
    "bomb-out-left",
    "bomb-out-right",
  ],
  "bounce": [
    "bounce-in-down",
    "bounce-in-left",
    "bounce-in-right",
    "bounce-in-up",
    "bounce-in",
    "bounce-out-down",
    "bounce-out-left",
    "bounce-out-right",
    "bounce-out-up",
    "bounce-out",
  ],
  "fade": [
    "fade-in-down-big",
    "fade-in-down",
    "fade-in-left-big",
    "fade-in-left",
    "fade-in-right-big",
    "fade-in-right",
    "fade-in-up-big",
    "fade-in-up",
    "fade-in",
    "fade-out-down-big",
    "fade-out-down",
    "fade-out-left-big",
    "fade-out-left",
    "fade-out-right-big",
    "fade-out-right",
    "fade-out-up-big",
    "fade-out-up",
    "fade-out",
  ],
  "flip": [
    "flip-in-x",
    "flip-in-y",
    "flip-out-x",
    "flip-out-y",
    "flip",
  ],
  "lightspeed": [
    "lightspeed-in",
    "lightspeed-out",
  ],
  "perspective": [
    "perspective-in-down",
    "perspective-in-left",
    "perspective-in-right",
    "perspective-in-up",
    "perspective-out-down",
    "perspective-out-left",
    "perspective-out-right",
    "perspective-out-up",
  ],
  "rotate": [
    "rotate-in-down-left",
    "rotate-in-down-right",
    "rotate-in-up-left",
    "rotate-in-up-right",
    "rotate-in",
    "rotate-out-down-left",
    "rotate-out-down-right",
    "rotate-out-down",
    "rotate-out-left",
    "rotate-out-right",
    "rotate-out-up-left",
    "rotate-out-up-right",
    "rotate-out-up",
    "rotate-out",
  ],
  "slide": [
    "slide-in-down",
    "slide-in-left",
    "slide-in-right",
    "slide-in-up",
    "slide-out-down",
    "slide-out-left",
    "slide-out-right",
    "slide-out-up",
  ],
  "space": [
    "space-in-down",
    "space-in-left",
    "space-in-right",
    "space-in-up",
    "space-out-down",
    "space-out-left",
    "space-out-right",
    "space-out-up",
  ],
  "special": [
    "hinge",
    "hole-out",
    "magic",
    "puff-in",
    "puff-out",
    "roll-in",
    "roll-out",
    "swap",
    "vanish-in",
    "vanish-out",
  ],
  "swash": [
    "swash-in",
    "swash-out",
  ],
  "tin": [
    "tin-in-down",
    "tin-in-left",
    "tin-in-right",
    "tin-in-up",
    "tin-out-down",
    "tin-out-left",
    "tin-out-right",
    "tin-out-up",
  ],
  "twister": [
    "twister-in-down",
    "twister-in-up",
  ],
  "zoom": [
    "zoom-in-down",
    "zoom-in-left",
    "zoom-in-right",
    "zoom-in-up",
    "zoom-in",
    "zoom-out-down",
    "zoom-out-left",
    "zoom-out-right",
    "zoom-out-up",
    "zoom-out",
  ],
};
